### ISSUE TITLE
Ubuntu 22.0.4

### ISSUE THREAD

**Issue by odehalaa** [Psychotropos/livevtt#2]
Hi,

Need to Thnaksyou first for amazing tool and nice idea, please I tried to use it on ubuntu 22.0.4 and python3 but I got a lot off error please if you can update or test it on Linux ,

Thanks a lot

**Comment by Psychotropos** [comment]
Hi,

Thanks for reporting this. I seemingly hadn't accounted for the fact that some conventions used in the script only worked under Python 3.12.

I've pushed some changes to the repository that should mean it now runs fine under Ubuntu 22.04 (which seems to use Python 3.10).

Hope this helps - I'll leave the issue open for now but please do report back if there's any more issues.

**Comment by odehalaa** [comment]
Hi,
Thanks for for your support,

Kindly as below the error

root@codero:~/livevtt# python3 main.py -u "http://192.168.1.85:9090/play/a02q/index.m3u8" -p 4040 -l 192.168.1.85
2024-07-10 18:25:21,576 INFO     Web server now listening on ('192.168.1.85', 4040)...
2024-07-10 18:25:25,887 INFO     Processing segment /http://192.168.1.85:9090/play/a02q/142799116_cbaf.ts...
2024-07-10 18:25:25,887 INFO     Processing segment /http://192.168.1.85:9090/play/a02q/142799119_4460.ts...
2024-07-10 18:25:25,887 INFO     Processing segment /http://192.168.1.85:9090/play/a02q/142799122_b6ca.ts...
2024-07-10 18:25:25,887 INFO     Processing segment /http://192.168.1.85:9090/play/a02q/142799125_f6f4.ts...
Traceback (most recent call last):
  File "/root/livevtt/main.py", line 236, in <module>
    transcribe_pool.map(partial(download_and_transcribe_wrapper, session=session, model=model,
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/root/livevtt/main.py", line 156, in download_and_transcribe_wrapper
    translated_chunk_paths[chunk_uri] = download_chunk_and_transcribe(session, model, chunk_url, chunk_uri,
  File "/root/livevtt/main.py", line 67, in download_chunk_and_transcribe
    start_ts = timedelta(seconds=float(subprocess.check_output(['ffprobe', '-i', chunk_fp.name, '-show_entries',
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffprobe', '-i', '/tmp/tmpcnbffl37/tmp3cytr2bv.ts', '-show_entries', 'stream=start_time', '-loglevel', 'quiet', '-select_streams', 'a:0', '-of', 'csv=p=0']' returned non-zero exit status 1.

**Comment by odehalaa** [comment]
root@codero:~/livevtt# python3 main.py -u "http://192.168.1.85:8089/Discover_ID_HD/video.m3u8" -p 4040 -l 192.168.1.85 --use-cuda=false
2024-07-10 18:39:51,177 INFO     Web server now listening on ('192.168.1.85', 4040)...
2024-07-10 18:39:55,234 INFO     Processing segment /2024/07/10/18/39/36-06440.ts...
2024-07-10 18:39:55,235 INFO     Processing segment /2024/07/10/18/39/42-06000.ts...
2024-07-10 18:39:55,235 INFO     Processing segment /2024/07/10/18/39/48-06000.ts...
2024-07-10 18:39:55,235 INFO     Processing segment /2024/07/10/18/39/54-06000.ts...
2024-07-10 18:39:55,436 INFO     Processing audio with duration 00:06.443
2024-07-10 18:39:55,481 INFO     Processing audio with duration 00:06.016
2024-07-10 18:39:55,546 INFO     Processing audio with duration 00:06.016
2024-07-10 18:39:55,583 INFO     Processing audio with duration 00:05.973
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Aborted (core dumped)

after changed the stream source

**Comment by Psychotropos** [comment]
Hi,

The first error will be to do with ffmpeg not having been installed (which I think you might've dealt with now). The second error is seemingly to do with faster-whisper trying to load in some CUDA libraries even when CUDA's not strictly required - see https://github.com/SYSTRAN/faster-whisper/issues/516.

Based on that aforementioned issue, it'd seem installing the libcuddn8 package as per https://github.com/SYSTRAN/faster-whisper/issues/516#issuecomment-2201088567 might resolve this.

**Comment by Psychotropos** [comment]
It does look like there might also have been a bug in handling the --use-cuda library with the script itself that's now fixed, so may be worth pulling the latest commits and trying it that way as well.

**Comment by odehalaa** [comment]
Hi,

Only one time working and after reboot my machine face same issues, please can you update the code install and configure the requirements please on Linux?
